import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const Layout = ({children}: Readonly<{children: React.ReactNode; }>) => (
    <html lang="en">
        <body className={inter.className}>{children}</body>
    </html>
);

export { metadata }
export default Layout;